# model params
backbone_type: resnet_v2_101
CUDA_VISIBLE_DEVICES: 0,1
loss_type: arcface
out_type: E

image_size: 112
embd_size: 512
class_num: 85742


# hyper params
bn_decay: 0.9
keep_prob: 0.4
weight_decay: !!float 5e-4
logits_scale: 64.0
logits_margin: 0.5
momentum: 0.9


# run params
val_bn_train: False
augment_flag: True
augment_margin: 16

gpu_num: 2
batch_size: 128
epoch_num: 20
step_per_epoch: 100000
val_freq: 2000

lr_steps: [100000, 200000, 400000]
lr_values: [0.004, 0.002, 0.0012, 0.0004]

# paths
pretrained_model:

train_data: ['hdfs://172.16.241.100:9000/data/mlib_data/tfrecords/MS1M-ArcFace/all.tfrecord']
val_data: {'agedb_30':'/data/agedb_30.bin','cfp_fp':'/data/cfp_fp.bin','cfp_ff':'/data/cfp_ff.bin','lfw': '/data/lfw.bin'}

output_dir: './output_config_ms1m_res101'

